# -*- coding: utf-8 -*-
"""calculadora

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rEPYTreCh2KgmTQOaShEXVJLOoy_pRYz
"""

print('*'*8,'CALCULADORA', '*'*8)
print()

while (True):
    num1 = int(input('Digite um número: '))
    print()
    num2 = int(input('Digite um número: '))
    print('''
    OPERADORES:
    [1] SOMA 
    [2] SUBTRAÇAO
    [3] MULTIPLICAÇÃO
    [4] DIVISÃO
    [5] SAIR''')
    
    print()
    operador = input('Escolha um operador: ')
    print()

    if operador == '1':
        operacao = num1 + num2
        print(f'A soma de {num1} e {num2} é {operacao}.')
        print()

    if operador == '2':
        operacao = num1 - num2
        print(f'A subtração de {num1} e {num2} é {operacao}.')
        print()

    if operador == '3':
            operacao = num1 * num2
            print(f'A multiplicação de {num1} e {num2} é {operacao}.')
            print()

    if operador == '4':
            operacao = num1 / num2
            print(f'A divisao de {num1} e {num2} é {operacao}.')
            print()

    if operador == '5':
            break